name: Craftattack2022
version: ${project.version}
main: ch.molhx.craftattack2022.Craftattack2022
api-version: 1.19
commands:
  state:
    usage: /state
    aliases:
      - status
  playtime:
    usage: /playtime
  website:
    usage: /website
    aliases:
      - web